version: '3.7'

services:

  swish-crawler-build:
    build:
      context: .
      target: prod
    image: swish-crawler:${IMAGE_TAG:-latest}

  swish-crawler-run:
    image: swish-crawler:${IMAGE_TAG:-latest}
    depends_on:
      - swish-crawler-minio
      - swish-crawler-minio-client
    volumes:
      - ./:/services/swish/swish-crawler/

  swish-crawler-test:
    image: swish-crawler:${IMAGE_TAG:-latest}
    depends_on:
      - swish-crawler-minio
    command: make test

  swish-crawler-minio:
    hostname: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  swish-crawler-minio-client:
    image: minio/mc:latest
    depends_on:
      - swish-crawler-minio
    entrypoint: /bin/sh
